### ISSUE TITLE
I did not get anything from 'Geoprepare' Function

### ISSUE THREAD

**Issue by umdsgy** [ritviksahajpal/geoprepare#6]
I used the following text to download NDVI images, but I did not get anything. The log file is also empty.

[DATASETS]
datasets = ['NDVI']

[PATHS]
dir_base = /gpfs/data1/cmongp1/Guanyuan/geoprepare_test
dir_input = ${dir_base}/input
dir_log = ${dir_base}/log
dir_interim = ${dir_input}/interim
dir_download = ${dir_input}/download
dir_metadata = ${dir_input}/metadata
dir_output = ${dir_base}/output
dir_global_datasets = ${dir_input}/global_datasets
dir_masks = ${dir_global_datasets}/masks
dir_regions = ${dir_global_datasets}/regions
dir_regions_shp = ${dir_regions}/shps
dir_crop_masks = ${dir_input}/crop_masks
dir_models = ${dir_input}/models

[AGERA5]
start_year = 2022

[NDVI]
product = MOD09CMG
vi = ndvi
scale_glam = False
scale_mark = True
print_missing = False

[LOGGING]
level = ERROR

[DEFAULT]
logfile = log
parallel_process = False
fraction_cpus = 0.5
start_year = 2022
end_year = 2023

**Comment by ritviksahajpal** [comment]
thanks! Can you share the python code you ran as well?

**Comment by ritviksahajpal** [comment]
fixed
